name: CI Checks

on:
  pull_request:
    branches: [ dev, stage, main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # ------------------------------
      # FRONTEND CHECKS
      # ------------------------------
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Test frontend
        working-directory: frontend
        run: npm test --if-present

      # ------------------------------
      # BACKEND CHECKS
      # ------------------------------
      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Test backend
        working-directory: backend
        run: npm test --if-present
