name: Deploy Backend (Production)

on:
  push:
    branches: [ main ]
    paths:
      - "backend/**"

jobs:
  deploy-backend-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment (Production)
        run: |
          curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID_PROD }}/deploys
