name: Deploy Backend (Stage)

on:
  push:
    branches: [ stage ]
    paths:
      - "backend/**"

jobs:
  deploy-backend-stage:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment (Stage)
        run: |
          curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID_STAGE }}/deploys
